"""Add registration_end to Race model

Revision ID: 35da2b8bfa82
Revises: 5e5e31b7c1d1
Create Date: 2025-04-15 12:09:48.918982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35da2b8bfa82'
down_revision = '5e5e31b7c1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_end', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('registration_end')

    # ### end Alembic commands ###
