"""Set default lap count for events

Revision ID: 44bd1077decf
Revises: c05641be3883
Create Date: 2025-04-17 14:41:56.718909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bd1077decf'
down_revision = 'c05641be3883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('laps',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('laps',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
