"""Add name to Runner

Revision ID: c05641be3883
Revises: 230cd36d182d
Create Date: 2025-04-17 14:34:08.146502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05641be3883'
down_revision = '230cd36d182d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('laps')

    # ### end Alembic commands ###
